In [2]:
import numpy as np

In [10]:
def array_factory(mode, shape, value=None):
   """
1. Checks the specified array generation mode.
2. Creates the array using the appropriate NumPy function (zeros, ones, full, or identity).
3. Returns the generated NumPy array or raises an error for unknown modes.
"""
   if mode == "zeros":
        return np.zeros(shape)
   elif mode == "ones":
        return np.ones(shape)
   elif mode == "full":
        return np.full(shape, value)
   elif mode == "identity":
        return np.eye(shape)
   else:
        raise ValueError(f"Unknown mode: {mode}")

In [11]:
def secure_reshape_and_stack(data1, data2, new_shape):
    """1. Validates and converts inputs to NumPy arrays.

    2. Reshapes the first dataset to a specific dimension.
    3. Vertically stacks both datasets into one matrix.
    """
    try:
        arr1 = np.array(data1)
        arr2 = np.array(data2)
        reshaped_arr1 = arr1.reshape(new_shape)
        combined_dataset = np.vstack((reshaped_arr1, arr2))
        return combined_dataset
    except ValueError as e:
        raise ValueError(f"Company-grade Error: {e}")

In [12]:
def apply_threshold(arr, threshold, replacement_value=-1):
    """1. Converts input data to a NumPy array.

    2. Checks which elements satisfy the condition (>= threshold).
    3. Replaces satisfying elements using np.where.
    """
    arr = np.array(arr)
    condition = arr >= threshold
    modified_arr = np.where(condition, replacement_value, arr)
    return modified_arr

In [14]:
# Regional Branch A (Flat sales data)
branch_a = [1, 2, 3, 4, 5, 6] 

# Regional Branch B (Already formatted 2x3 matrix)
branch_b = [[7, 8, 9], 
            [10, 11, 12]]

# Reshape A to 2x3 and stack with B
final_report = secure_reshape_and_stack(branch_a, branch_b, (2, 3))
print(final_report)
# Resulting shape: (4, 3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [15]:
v= np.array([1,2,3])
apply_threshold(v,2,-20)


array([  1, -20, -20])